[package]
name = "daedalus"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
libaes = "0.6.4"
anyhow = "1.0.58"
clap = { version = "3.2.23", features = ["derive"] }
rand = "0.8.5"
blake3 = "1.3.3"